;
; File generated by cc65 v 2.19 - Git 884f72637
;
	.fopt		compiler,"cc65 v 2.19 - Git 884f72637"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/enemies.c", 647, 1664659798
	.dbg		file, "src/directions.h", 104, 1664659464
	.dbg		file, "src/enemies.h", 200, 1664659909
	.dbg		file, "src/globals.h", 543, 1664622739
	.dbg		file, "src/subrand.h", 146, 1664641459
	.dbg		sym, "i", "00", extern, "_i"
	.export		_init_enemies
	.export		_update_enemies
	.export		_render_enemies
	.importzp	_i
	.export		_enemy_x
	.export		_enemy_y
	.export		_enemy_direction
	.export		_enemy_sx
	.export		_enemy_sy
	.export		_enemy_type
	.export		_enemy_hp

.segment	"BSS"

_enemy_x:
	.res	32,$00
_enemy_y:
	.res	32,$00
_enemy_direction:
	.res	16,$00
_enemy_sx:
	.res	32,$00
_enemy_sy:
	.res	32,$00
_enemy_type:
	.res	16,$00
_enemy_hp:
	.res	16,$00

; ---------------------------------------------------------------
; void __near__ init_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_enemies: near

	.dbg	func, "init_enemies", "00", extern, "_init_enemies"

.segment	"CODE"

;
; for(i = 0; i < MAX_ENEMIES; i++) {
;
	.dbg	line, "src/enemies.c", 19
	lda     #$00
	sta     _i
L0007:	lda     _i
	cmp     #$10
	bcs     L0003
;
; enemy_hp[i] = 0;
;
	.dbg	line, "src/enemies.c", 20
	ldy     _i
	lda     #$00
	sta     _enemy_hp,y
;
; for(i = 0; i < MAX_ENEMIES; i++) {
;
	.dbg	line, "src/enemies.c", 19
	inc     _i
	jmp     L0007
;
; }
;
	.dbg	line, "src/enemies.c", 22
L0003:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ update_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_enemies: near

	.dbg	func, "update_enemies", "00", extern, "_update_enemies"

.segment	"CODE"

;
; for(i = 0; i < MAX_ENEMIES; i++) {
;
	.dbg	line, "src/enemies.c", 26
	lda     #$00
	sta     _i
L0008:	lda     _i
	cmp     #$10
	bcs     L0003
	inc     _i
	jmp     L0008
;
; }
;
	.dbg	line, "src/enemies.c", 30
L0003:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ render_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_render_enemies: near

	.dbg	func, "render_enemies", "00", extern, "_render_enemies"

.segment	"CODE"

;
; }
;
	.dbg	line, "src/enemies.c", 34
	rts

	.dbg	line
.endproc

